"""Adding admin_id column to TeamMember

Revision ID: 3f7c6d07591d
Revises: ca4f3d199332
Create Date: 2021-12-22 13:46:06.069574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7c6d07591d'
down_revision = 'ca4f3d199332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'admin_id')
    # ### end Alembic commands ###
