"""Add invited status column

Revision ID: 6779bebb64e6
Revises: b31a046bfa53
Create Date: 2021-12-21 14:22:57.669802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6779bebb64e6'
down_revision = 'b31a046bfa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invite_status')
    # ### end Alembic commands ###
