"""Add missing ticket_id column

Revision ID: b31a046bfa53
Revises: 1b57e397deea
Create Date: 2021-12-21 10:55:11.016295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31a046bfa53'
down_revision = '1b57e397deea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'ticket_id')
    # ### end Alembic commands ###
