"""Adding teammembers table

Revision ID: ca4f3d199332
Revises: 51387d8fda8d
Create Date: 2021-12-22 13:35:12.093544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4f3d199332'
down_revision = '51387d8fda8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_members_admin_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_column('team_members', 'admin_id')
    op.add_column('users', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'team_members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'member_id')
    op.add_column('team_members', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_admin_id_fkey', 'team_members', 'users', ['admin_id'], ['id'])
    op.drop_column('team_members', 'user_id')
    # ### end Alembic commands ###
