"""Adding team ID to ticket table

Revision ID: cb382e6d4f2b
Revises: d33cebc88939
Create Date: 2021-12-23 12:35:28.995225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb382e6d4f2b'
down_revision = 'd33cebc88939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('team_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'team_id')
    # ### end Alembic commands ###
