"""Updating member table, adding team_name and user_id

Revision ID: d33cebc88939
Revises: 3f7c6d07591d
Create Date: 2021-12-22 17:44:32.813445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33cebc88939'
down_revision = '3f7c6d07591d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('team_name', sa.String(), nullable=True))
    op.drop_constraint('team_members_team_id_fkey', 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_name'], ['team_name'])
    op.drop_column('team_members', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('team_id', sa.String(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_column('team_members', 'team_name')
    # ### end Alembic commands ###
